repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: 99abe27a5a16f301d9e0a3828181399dfbf54ebd
    hooks:
    -   id: ruff 
        types_or: [ python, pyi ]
        args: [ --fix ]
-   repo: https://github.com/psf/black.git
    rev: d82da0f0e9151bc9afae381f803948fe5836c084
    hooks:
    -   id: black

